### PR TITLE
Multiple outputs for an alternative package name with _ instead of -

### PR DESCRIPTION
**Pull request by cheginit**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cheginit** [comment]
@conda-forge-admin, please rerender

**Comment by cheginit** [comment]
@conda-forge-admin, please rerender

**Comment by cheginit** [comment]
@JWCook Do you who should we ping here from the `conda-forge` team for help with this issue?

**Comment by JWCook** [comment]
In the past I've gone to the [Conda-Forge chat on Gitter](https://gitter.im/conda-forge/conda-forge.github.io) for help.

**Comment by cheginit** [comment]
I did post a message there, but unfortunately didn't get any response.

**Pull request closed without merging**
