### PR TITLE
Use typing-extension as a reference to fix the backends module issue

### PR DESCRIPTION
**Pull request by cheginit**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cheginit** [comment]
@JWCook Do you know why this fails with `ModuleNotFoundError: No module named 'aiohttp_client_cache.backends'`? I couldn't figure it out. I even used `type-extension`'s `meta.yaml` file to ensure it's correct, but still it's not working.

**Comment by cheginit** [comment]
@JWCook I think it's better if I revert the multiple outputs for now, and open a new PR with it, so we can have a working build until we find a fix.

**Comment by JWCook** [comment]
That's strange. I looked at the build logs, and don't see anything obvious that would cause that. I'm fine with reverting it for now.

**Comment by cheginit** [comment]
Yeah, that's strange. I even looked at the `pyproject.toml` file to check maybe there's something that cause the issue. Maybe, we should ping one of the `conda-forge` team members and ask what seems to be the issue. The strange thing is that when I run `conda build .` locally (macOS), it works fine and builds both packages but on Azure which is Linux, it fails.

**Pull request merged**
